### ISSUE TITLE
Note: Maybe a descending order for the versions could be the more common case  

### ISSUE THREAD

**Issue by bowman2001** [jmooring/hvm#61]
This is only a suggestive note of my first impression using HVM: I would expect the last, most recent version as the first one in the list. 

I’ve changed the behavior with the environment variable as you described and all works fine. I just think that maybe other users would also expect the default the other way around.

**Comment by jmooring** [comment]
Thanks for the feedback.

This started as a Bash script several years ago, used only by me, to rapidly bisect releases to find where a given behavior started or ended. A few months ago I converted it to this Go app.

To rapidly bisect, I need to see everything (numTagsToDisplay = -1) since v0.54.0.  That's currently 169 releases, taking 57 rows in the console. And my console, either native default or within VS code, is never that tall, and I don't want to scroll to see the latest.

In that this is a configurable behavior, I am closing this.

**Comment by jmooring** [comment]
@bowman2001 You are right, and you are the second person to mention this. I'll change the default behavior in the next release. I'm probably the only person who will ever use this for bisection, listing all the releases.
