### ISSUE TITLE
enhancement: allow bypassing the selection screen to install latest version

### ISSUE THREAD

**Issue by irkode** [jmooring/hvm#85]
real great thing - loveIt

works flawlesly on my Windows 11 box with Powershell Core 7.4.2
thx for that - no longer puzzeling around with wget/choco/winget or manual download

---
## Enhancement: allow bypassing the selection screen to install latest version

I implemented a new switch `--useLatest` to bypass selection screen

- `hvm use --useLatest`
- `hvm install --useLatest`

see [(https://github.com/jmooring/hvm/compare/main...irkode:hvm:use-latest)](https://github.com/jmooring/hvm/compare/main...irkode:hvm:use-latest)

maybe it's something you would like (switch imho could be named --latest)

```text
PS \forks\hvm> hvm status
Version management is disabled in the current directory.
The cache is empty.

PS \forks\hvm> hvm use --useLatest
Downloading v0.126.1... done.

PS \forks\hvm> hvm status
The current directory is configured to use Hugo v0.126.1.
Cached versions of the Hugo executable:

v0.126.1

Cache size: 87 MB
Cache directory: C:\Users\rik\AppData\Local\hvm
```
p.s. any reason why you don't spread that around in the Forum, tips&tricks ...

**Comment by jmooring** [comment]
> maybe it's something you would like

Please submit a PR using a `--latest` flag (not `--useLatest`), and I'll take it for a test drive. I've also considered (for my benefit) getting the latest version as the default with `use` and `install` UI (i.e., press Return and you'll get the latest), but that's a separate enhancement.

> any reason why you don't spread

I created this several years ago as a Bash script. Its sole purpose was to rapidly bisect releases to determine when a given behavior appeared or disappeared. Very few users (perhaps just me) need this capability.

I migrated the app from Bash to Go primarily as a learning exercise, but quickly determined that additional capabilities were relatively cheap (e.g., use it as a standalone installer, automatic downloads, etc.). So yes, it is now useful for a larger percentage of the user population.

However, the user population includes expert, intermediate, and novice users. Many of these users, including some advanced users:

- Have no concept of PATH
- Have no idea how to safely or persistently change their PATH
- Have no concept of overloading an executable call with an alias

I have zero interest in actively promoting this as a general purpose installer because I don't want to support the above.

**Comment by jmooring** [comment]
Closed with https://github.com/jmooring/hvm/pull/86.
